name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Thiết lập Node.js (thích hợp cho ứng dụng Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Bước 3: Cài đặt các dependencies
      - name: Install dependencies
        run: npm install

      # Bước 4: Build ứng dụng (nếu có lệnh build)
      - name: Build project
        run: npm run build

      # Bước 5: Deploy lên server qua SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/app   # Thay bằng đường dẫn của ứng dụng trên server
            git pull origin main    # Lấy bản cập nhật mới nhất từ GitHub
            npm install             # Cài đặt lại các dependencies
            npm run build           # Build lại ứng dụng (nếu cần)
            pm2 restart app         # Restart ứng dụng (nếu dùng PM2)
